name: Cypress testing

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    index-edge:
        runs-on: ubuntu-22.04
        name: index.html E2E on Edge
    steps:
		- uses: actions/checkout@v4
        - uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: cypress/e2e/index.cy.js