name: Cypress testing

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: |
            cypress/e2e/404.cy.js
            cypress/e2e/contact.cy.js
            cypress/e2e/index.cy.js
            cypress/e2e/portfolio.cy.js
